version: "3.7"

services:
  # Backend API
  smart-brain-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    environment:
      POSTGRES_URI: postgres://sally:secret@postgres:5432/smart-brain-docker
      REDIS_URI: redis://redis:6379
    networks:
      static-network:
        ipv4_address: 172.20.128.2
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/smart-brain-api

  # Postgres
  postgres:
    environment:
      POSTGRES_USER: sally
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    build: ./postgres
    networks:
      static-network:
        ipv4_address: 172.20.128.10
    ports:
      - "5432"

  # Redis
  redis:
    image: redis
    networks:
      static-network:
        ipv4_address: 172.20.128.20
    ports:
      - "6379:6379"

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
